[build]
builder = "paketobuildpacks/builder:base"

[deploy]
startCommand = "java -jar target/hotelbooking-0.0.1-SNAPSHOT.jar"

[env]
# Replace these values via Railway's "Variables" dashboard (not in code)
MONGODB_URI = "mongodb+srv://<username>:<password>@cluster1.mongodb.net/hotelbooking?retryWrites=true&w=majority"
